export const BANNER_MESSAGE: string | null =
  "ALL ORDERS PLACED NOW WILL NOT START SHIPPING UNTIL AUGUST 1ST. CUSTOM & RX ORDERS WILL START SHIPPING AUGUST 8TH."

export const CART_MESSAGE: string | null =
  "ALL ORDERS PLACED NOW WILL NOT START SHIPPING UNTIL AUGUST 1ST. CUSTOM & RX ORDERS WILL START SHIPPING AUGUST 8TH."
