export const clearanceProductHandles = [
  'waycooler',
  'the-45s',
  'ultra-lux',
  'upstart',
  'big-iron-ii-black-smoke',
  'petrillo',
  '101er',
  'cleo',
  'harlow',
  'le-saboteur',
  'bombshell',
  'waycooler-mooneyes-x-tres-noir',
  'the-45s-mooneyes-x-tres-noir',
];
